### PR TITLE
Add a ANSI text test babashka script

### PR DESCRIPTION
**Pull request by lread**
Prints text SGR effects for visual inspection.

Should help with #8

### CODE REVIEW

**Comment by lread** [comment]
Had to create a wrapper script.sh with:
```bash
script/ansi-text-test.clj
```
Then ran:
```
clj -M:membrane.term screenshot --play script.sh --height 51 --width 133 --line-delay 1 --final-delay 50
```

Which resulted in `terminal.png`:
image

**Comment by lread** [comment]
Think I'll do one more commit.

**Comment by lread** [comment]
Yeah I think things are now clearer. Here's a new membrane.term generated screenshot:
image

**Comment by lread** [comment]
@phronmophobic if you think this is a handy script too, I feel it is fine to merge.

**Review by phronmophobic — APPROVED** [review]
Sounds good.

**Pull request merged**
